### ISSUE TITLE
Escape output against quotation character

### ISSUE THREAD

**Issue by mondeja** [kceb/git-message-action#7]
If I've the message `Foo ' bar` in a commit I can retrieve it as output of this action escaping it with `printf "${{ steps.commit.outputs.git-message }}"` (wrapping the commit message between double quotes `"`). If the quote character in the commit is `"`, I can escape it wrapping with single quotes retrieving the output, but if I've single and double quotes in the commit message, every escaping attempt results impossible:

- `Foo ' bar` -> `COMMIT_MSG="$(printf "${{ steps.commit.outputs.git-message }}")"`
- `Foo " bar` -> `COMMIT_MSG="$(printf '${{ steps.commit.outputs.git-message }}')"`
- `Foo " bar ' baz` -> `COMMIT_MSG="$(printf "${{ steps.commit.outputs.git-message }}")"` ->  `ERROR: unexpected EOF while looking for matching...`

If this action could manage the escape of a character (for example, replace `"` by `\"` in output), this problem would be solved:

- `Foo \" bar ' baz` -> `COMMIT_MSG="$(printf '${{ steps.commit.outputs.git-message }}')"`

Maybe I'm missing another way to solve this problem? Thank you.

**Comment by ericcornelissen** [comment]
First, I don't think replacing either `"` by `\"` or `'` by `\'` is a suitable solution as that doesn't work for YAML, e.g.:

```yaml
foo: |
  foo " bar
  hello \" world
```

becomes

```json
{
  "foo": "foo \" bar\nhello \\\" world\n"
}
```

Hence, using the output value in YAML (I think a more common use case than using it in `printf`, especially with [v1.2.0](https://github.com/kceb/git-message-action/releases/tag/v1.2.0)) would no longer work as expected.

---

I've instead been looking at generalizing the somewhat related fix of https://github.com/simple-icons/simple-icons/pull/6071 to this problem by replacing `"` by `%22` and `'` by `%27` (following [this table](https://www.w3schools.com/tags/ref_urlencode.ASP)). In particular I applied the following function to the output values:

```js
function escape(s) {
  return s
    .replace(/%/g, "%25")
    .replace(/\n/g, "%0A")
    .replace(/\r/g, "%0D")
    .replace(/"/g, "%22")
    .replace(/'/g, "%27");
}
```

However, it seems that is not generally applicable as it seems these characters are only decoded when using the `::set-output` "function".

As such, I can't think of a general solution that works for all scenarios. Since your use case for using `printf` has (I believe) been resolved by #6, I will go ahead and close this now. If you or anyone else still thinks this "bug" should be fixed, please feel free to leave a comment here. And either include (a) _why_ you're trying to `printf` the commit message or (b) a potential fix.
